export const InteractionConfig = {
  INITIAL_SCALE: 1,
  HOVER_DETECT_RADIUS: 5,
  MIN_ZOOM: 0.1,
  MAX_ZOOM: 10,
  ZOOM_SPEED: 0.1,
  ZOOM_TO_POINTER: true,
  ENABLE_PAN: true,
  DOUBLE_CLICK_THRESHOLD: 300,
}
